### ISSUE TITLE
Review Production new starter queries to establish priority for Wiki completion

### ISSUE THREAD

**Issue by JGilbert-eLife** [elifesciences/eLife-JATS-schematron#104]
- [x] Go through slack channels for queries
- [x] Make document with queries

**Comment by naushinthomson** [comment]
- Deciding which funder to use when there are sub-departments e.g. EU2020, NIH, NIH Office of the director etc. when it isn't clear in the manuscript/submission info.
- When/whether to keep single math elements or change them to letters
- ‘citation is preceded by text containing much of the citation text which is possibly unnecessary - We determined the final number of clusters by using the Thorndike procedure (Thorndike, 1953)’ type errors - how to decide if its unnecessary
- Adding dataset information - when is it RCSB, EMDB, PDB, EBI since they all seem linked?
- ‘There is no xref from a contrib pointing to this award-group’ type errors
- When/whether to label part labels in figures (A (I), A, (II))
